// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

/**
 * 根据数据库连接自动选择 Prisma schema 与迁移目录。
 * 本地开发默认使用 SQLite，Render 生产环境使用 PostgreSQL。
 */
function resolvePrismaRuntime() {
  const databaseUrl = process.env.DATABASE_URL || 'file:./dev.db';
  const isPostgres = /^(postgres|postgresql|prisma\+postgres):/i.test(databaseUrl);

  return {
    databaseUrl,
    schema: isPostgres ? 'prisma/schema.postgresql.prisma' : 'prisma/schema.sqlite.prisma',
    migrationsPath: isPostgres ? 'prisma/migrations/postgresql' : 'prisma/migrations/sqlite',
  };
}

const prismaRuntime = resolvePrismaRuntime();

export default defineConfig({
  schema: prismaRuntime.schema,
  migrations: {
    path: prismaRuntime.migrationsPath,
  },
  datasource: {
    url: prismaRuntime.databaseUrl,
  },
});
